package goldenhookfishing;

/**
 *
 * @author Haozhen Li
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MenuFrame() {
        initComponents();
        // spawn the frame in center of monitor
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        playButton = new javax.swing.JButton();
        ruleButton = new javax.swing.JButton();
        menuTitleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        menuPanel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 45, 55));

        playButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        playButton.setText("Play Game");
        playButton.setFocusPainted(false);
        playButton.setMaximumSize(new java.awt.Dimension(150, 50));
        playButton.setMinimumSize(new java.awt.Dimension(150, 50));
        playButton.setPreferredSize(new java.awt.Dimension(150, 50));
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        menuPanel.add(playButton);

        ruleButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ruleButton.setText("Game Rule");
        ruleButton.setToolTipText("");
        ruleButton.setFocusPainted(false);
        ruleButton.setPreferredSize(new java.awt.Dimension(150, 50));
        ruleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleButtonActionPerformed(evt);
            }
        });
        menuPanel.add(ruleButton);

        menuTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        menuTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTitleLabel.setText("Golden Hook Fishing");
        menuTitleLabel.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(menuTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(menuTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // dispose menu frame, open game frame, and start new game
    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameFrame gameFrame = new GameFrame();
                gameFrame.setResizable(false); // fix window size
                gameFrame.setVisible(true);
                MenuFrame.this.setVisible(false);
                MenuFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_playButtonActionPerformed

    private void ruleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel menuTitleLabel;
    private javax.swing.JButton playButton;
    private javax.swing.JButton ruleButton;
    // End of variables declaration//GEN-END:variables
}
